name: ma_guinee
description: "Plateforme moderne multi-services pour la Guinée."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Cartes & géolocalisation
  flutter_map: ^8.2.2
  latlong2: ^0.9.0
  flutter_map_marker_cluster: ^8.2.2
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  google_maps_flutter: ^2.7.0
  google_maps_flutter_web: ^0.5.7

  # Requêtes HTTP
  http: ^1.2.1

  # Supabase / état
  supabase_flutter: ^2.6.0
  provider: ^6.1.2
  postgrest: ^2.1.3

  # Notifications (push + locales)
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3
  flutter_local_notifications: ^19.5.0   # ✅ MAJ pour compatibilité
  timezone: ^0.10.1

  # Infos appareil / app
  device_info_plus: ^10.1.0
  package_info_plus: ^8.0.2

  # Partage & ouverture externe
  share_plus: ^12.0.1
  url_launcher: ^6.3.0

  # Sélecteurs / fichiers
  image_picker: ^1.1.2
  country_picker: ^2.0.25
  file_picker: ^10.3.3
  path: ^1.9.0
  mime: ^2.0.0

  # UI & composants
  photo_view: ^0.15.0
  carousel_slider: ^5.1.1
  font_awesome_flutter: ^10.7.0
  universal_html: ^2.2.4
  cached_network_image: ^3.4.1
  flutter_svg: ^2.0.10+1
  responsive_framework: ^1.1.1
  transparent_image: ^2.0.1
  intl: ^0.20.2

  # Vidéo
  chewie: ^1.7.1
  video_player: ^2.9.1

  # QR / Scanner
  qr_flutter: ^4.1.0
  mobile_scanner: ^7.1.3
  qr_code_scanner: ^1.0.1

  # Permissions (caméra, localisation, stockage…)
  permission_handler: ^12.0.1

  # PDF / impression / ouverture de fichiers
  pdf: ^3.10.7
  printing: ^5.13.4
  path_provider: ^2.1.4
  open_filex: ^4.4.0

  # Cache persistant
  shared_preferences: ^2.2.3

  # Caméra
  camera: ^0.10.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/default_avatar.png
    - assets/logo_guinee.png
    - assets/nimba.png
    - assets/carte_guinee.png
    - assets/jobs/hero.png
    - assets/jobs/card_cover.png
    - assets/fonts/Inter_24pt-Regular.ttf
    - assets/fonts/Inter_24pt-Bold.ttf
